version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
    volumes:
      - postgres_14_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build: .
    restart: unless-stopped
    container_name: nodejs-app-container
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  postgres_14_data:
